// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlCE2XYlglZLbMHtVi_6H1AgZTI0Viks',
    appId: '1:828341791788:web:e91353aa672de603423589',
    messagingSenderId: '828341791788',
    projectId: 'tweaki-communication-app',
    authDomain: 'tweaki-communication-app.firebaseapp.com',
    storageBucket: 'tweaki-communication-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjXyf_Fp4G7PZYa7qvEiGuYoOj7gjsxE',
    appId: '1:828341791788:android:396c47c1be234f5e423589',
    messagingSenderId: '828341791788',
    projectId: 'tweaki-communication-app',
    storageBucket: 'tweaki-communication-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3X1WtQCEAI9TfL3BgODwS4ze8L2-Zq1Y',
    appId: '1:828341791788:ios:db377936c0db663a423589',
    messagingSenderId: '828341791788',
    projectId: 'tweaki-communication-app',
    storageBucket: 'tweaki-communication-app.appspot.com',
    iosBundleId: 'com.example.tweaki',
  );
}
